<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="9" total="21" passed="8" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-06-20T09:49:59Z" name="Calculator Test Suite" finished-at="2019-06-20T09:50:54Z" duration-ms="55274">
    <groups>
    </groups>
    <test started-at="2019-06-20T09:49:59Z" name="Calculator Test Parameterization" finished-at="2019-06-20T09:50:54Z" duration-ms="55274">
      <class name="com.winiumdemo.calculator.Mod">
        <test-method signature="testMod(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.winiumdemo.calculator.Mod@1b1473ab]" started-at="2019-06-20T09:50:34Z" name="testMod" description="Verify Mod of Two Numbers" data-provider="Modulus" finished-at="2019-06-20T09:50:38Z" duration-ms="3958" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[55]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMod -->
        <test-method signature="testMod(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.winiumdemo.calculator.Mod@1b1473ab]" started-at="2019-06-20T09:50:38Z" name="testMod" description="Verify Mod of Two Numbers" data-provider="Modulus" finished-at="2019-06-20T09:50:42Z" duration-ms="3466" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[34]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMod -->
        <test-method signature="testMod(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.winiumdemo.calculator.Mod@1b1473ab]" started-at="2019-06-20T09:50:42Z" name="testMod" description="Verify Mod of Two Numbers" data-provider="Modulus" finished-at="2019-06-20T09:50:45Z" duration-ms="3709" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[45]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[6]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual modulus is 3 Expected modulus is 6 expected [6] but found [3]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual modulus is 3 Expected modulus is 6 expected [6] but found [3]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at com.winiumdemo.calculator.Mod.testMod(Mod.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMod -->
      </class> <!-- com.winiumdemo.calculator.Mod -->
      <class name="com.winiumdemo.calculator.Addition">
        <test-method is-config="true" signature="setUpBeforeSuite()[pri:0, instance:com.winiumdemo.calculator.Addition@3aefe5e5]" started-at="2019-06-20T09:49:54Z" name="setUpBeforeSuite" finished-at="2019-06-20T09:49:59Z" duration-ms="4401" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeSuite -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.winiumdemo.calculator.Addition@3aefe5e5]" started-at="2019-06-20T09:49:59Z" name="setUp" finished-at="2019-06-20T09:50:04Z" duration-ms="5406" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testAddition(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.winiumdemo.calculator.Addition@3aefe5e5]" started-at="2019-06-20T09:50:05Z" name="testAddition" description="Verify Addition of Two Numbers" data-provider="Addition" finished-at="2019-06-20T09:50:09Z" duration-ms="4093" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[20]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddition -->
        <test-method signature="testAddition(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.winiumdemo.calculator.Addition@3aefe5e5]" started-at="2019-06-20T09:50:09Z" name="testAddition" description="Verify Addition of Two Numbers" data-provider="Addition" finished-at="2019-06-20T09:50:13Z" duration-ms="4226" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[30]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[40]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[70]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddition -->
        <test-method signature="testAddition(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.winiumdemo.calculator.Addition@3aefe5e5]" started-at="2019-06-20T09:50:13Z" name="testAddition" description="Verify Addition of Two Numbers" data-provider="Addition" finished-at="2019-06-20T09:50:19Z" duration-ms="6052" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[400]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[450]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[900]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual addition is 850 Expected addition is 900 expected [900] but found [850]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual addition is 850 Expected addition is 900 expected [900] but found [850]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at com.winiumdemo.calculator.Addition.testAddition(Addition.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddition -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.winiumdemo.calculator.Addition@3aefe5e5]" started-at="2019-06-20T09:50:54Z" name="tearDown" finished-at="2019-06-20T09:50:54Z" duration-ms="30" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.winiumdemo.calculator.Addition -->
      <class name="com.winiumdemo.calculator.Square">
        <test-method signature="testSquare(java.lang.String, java.lang.String)[pri:0, instance:com.winiumdemo.calculator.Square@2f7c2f4f]" started-at="2019-06-20T09:50:46Z" name="testSquare" description="Verify Sqaure of  Numbers" data-provider="square" finished-at="2019-06-20T09:50:49Z" duration-ms="2904" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[65536]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSquare -->
        <test-method signature="testSquare(java.lang.String, java.lang.String)[pri:0, instance:com.winiumdemo.calculator.Square@2f7c2f4f]" started-at="2019-06-20T09:50:49Z" name="testSquare" description="Verify Sqaure of  Numbers" data-provider="square" finished-at="2019-06-20T09:50:51Z" duration-ms="2673" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[390625]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSquare -->
        <test-method signature="testSquare(java.lang.String, java.lang.String)[pri:0, instance:com.winiumdemo.calculator.Square@2f7c2f4f]" started-at="2019-06-20T09:50:51Z" name="testSquare" description="Verify Sqaure of  Numbers" data-provider="square" finished-at="2019-06-20T09:50:54Z" duration-ms="2682" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[6]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[36]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual square is 1679616 Expected square is 36 expected [36] but found [1679616]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual square is 1679616 Expected square is 36 expected [36] but found [1679616]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at com.winiumdemo.calculator.Square.testSquare(Square.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSquare -->
      </class> <!-- com.winiumdemo.calculator.Square -->
      <class name="com.winiumdemo.calculator.Division">
        <test-method signature="testDivision(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.winiumdemo.calculator.Division@149e0f5d]" started-at="2019-06-20T09:50:20Z" name="testDivision" description="Verify Division of Two Numbers" data-provider="Division" finished-at="2019-06-20T09:50:25Z" duration-ms="4962" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[100]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDivision -->
        <test-method signature="testDivision(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.winiumdemo.calculator.Division@149e0f5d]" started-at="2019-06-20T09:50:25Z" name="testDivision" description="Verify Division of Two Numbers" data-provider="Division" finished-at="2019-06-20T09:50:29Z" duration-ms="4127" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[250]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[50]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDivision -->
        <test-method signature="testDivision(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.winiumdemo.calculator.Division@149e0f5d]" started-at="2019-06-20T09:50:29Z" name="testDivision" description="Verify Division of Two Numbers" data-provider="Division" finished-at="2019-06-20T09:50:34Z" duration-ms="5339" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[200]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[100]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual division is 2 Expected Division is 3 expected [3] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual division is 2 Expected Division is 3 expected [3] but found [2]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at com.winiumdemo.calculator.Division.testDivision(Division.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDivision -->
      </class> <!-- com.winiumdemo.calculator.Division -->
    </test> <!-- Calculator Test Parameterization -->
  </suite> <!-- Calculator Test Suite -->
</testng-results>
